set(_CATKIN_CURRENT_PACKAGE "demo01_ws")
set(demo01_ws_VERSION "0.0.0")
set(demo01_ws_MAINTAINER "dream <dream@todo.todo>")
set(demo01_ws_PACKAGE_FORMAT "2")
set(demo01_ws_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(demo01_ws_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(demo01_ws_BUILDTOOL_DEPENDS "catkin")
set(demo01_ws_BUILDTOOL_EXPORT_DEPENDS )
set(demo01_ws_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(demo01_ws_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(demo01_ws_TEST_DEPENDS )
set(demo01_ws_DOC_DEPENDS )
set(demo01_ws_URL_WEBSITE "")
set(demo01_ws_URL_BUGTRACKER "")
set(demo01_ws_URL_REPOSITORY "")
set(demo01_ws_DEPRECATED "")